"""The Rust MCP server compiles in copies of two Python contracts.

Both are generated by `backend/native/lumen-mcp-server/scripts/export_contracts.py`.
These tests fail when the committed copies drift from the Python definitions, so
the Rust server cannot silently fall behind a new connector or a changed tool
signature.
"""

import asyncio
import json
from pathlib import Path

from lumen.configs.constants import DocumentSource

_DATA_DIR = Path(__file__).resolve().parents[4] / "native" / "lumen-mcp-server" / "data"
_GENERATOR = "backend/native/lumen-mcp-server/scripts/export_contracts.py"
_REGENERATE = f"Regenerate it with: uv run python {_GENERATOR}"


def _load(name: str) -> object:
    path = _DATA_DIR / name
    assert path.is_file(), f"{path} is missing; run {_GENERATOR}"
    return json.loads(path.read_text(encoding="utf-8"))


def test_exported_document_sources_match_the_enum() -> None:
    exported = _load("document_sources.json")
    expected = sorted(member.value for member in DocumentSource)

    assert exported == expected, (
        f"The Rust MCP server's DocumentSource copy is stale. {_REGENERATE}"
    )


def test_exported_tool_schemas_match_fastmcp() -> None:
    from lumen.mcp_server.api import mcp_server

    tools = asyncio.run(mcp_server._list_tools())
    expected = {tool.name: tool.parameters for tool in tools}

    exported = _load("tool_schemas.json")
    assert exported == expected, (
        f"The Rust MCP server's tool schemas are stale. {_REGENERATE}"
    )
