"""The Rust gate compiles in a copy of the external-app action catalog.

It is generated by `backend/native/lumen-sandbox-proxy/scripts/export_catalog.py`.
These tests fail when the committed copy drifts from the Python providers, so
the Rust matcher cannot silently decide with a stale catalog — which would mean
a new action forwarding ungated, or an admin's policy override missing its
action.
"""

import json
from pathlib import Path

from lumen.db.enums import ExternalAppType
from lumen.external_apps.providers.registry import (
    PROVIDERS,
    uses_cloud_scope,
    validate_action_policies,
)

_CRATE_DIR = Path(__file__).resolve().parents[4] / "native" / "lumen-sandbox-proxy"
_CATALOG_PATH = _CRATE_DIR / "data" / "action_catalog.json"
_GENERATOR = "backend/native/lumen-sandbox-proxy/scripts/export_catalog.py"
_REGENERATE = f"Regenerate it with: uv run python {_GENERATOR}"


def _exported() -> dict:
    assert _CATALOG_PATH.is_file(), f"{_CATALOG_PATH} is missing; run {_GENERATOR}"
    loaded = json.loads(_CATALOG_PATH.read_text(encoding="utf-8"))
    assert isinstance(loaded, dict)
    return loaded


def test_exported_catalog_matches_the_providers() -> None:
    """The whole file, rebuilt from the registry and compared."""
    import sys

    sys.path.insert(0, str(_CRATE_DIR / "scripts"))
    from export_catalog import build_catalog  # noqa: PLC0415

    assert _exported() == build_catalog(), (
        f"The Rust gate's action catalog is stale. {_REGENERATE}"
    )


def test_exported_catalog_covers_every_registered_provider() -> None:
    """A newly registered provider must reach the Rust gate.

    Rebuilding the file from the same function cannot catch a provider the
    exporter never reaches, so the provider set is asserted separately.
    """
    exported = {app["app_type"] for app in _exported()["apps"]}
    registered = {app_type.value for app_type in PROVIDERS}

    assert exported == registered, (
        f"The Rust gate's provider set is stale. {_REGENERATE}"
    )


def test_exported_action_ids_are_the_ids_the_admin_api_accepts() -> None:
    """The ids must be the catalog values, not their enum reprs.

    ``EndpointSpec.id`` is a ``str``-mixin enum member: ``str()`` on one renders
    ``"ClassName.MEMBER"`` while the database, the policy map and the admin API
    all key on the value. Validating the exported ids against the admin API's
    own check ties the two together, so an exporter that renders them the wrong
    way fails here instead of silently voiding every stored override.
    """
    for app in _exported()["apps"]:
        app_type = ExternalAppType(app["app_type"])
        # The file carries the full catalog; the admin API offers the
        # cloud-filtered view, so drop the actions this deployment withholds.
        cloud = uses_cloud_scope(app_type)
        ids = [
            action["id"]
            for action in app["actions"]
            if not (cloud and action["requires_self_hosted_scope"])
        ]
        # Raises on any id outside this app_type's catalog.
        validate_action_policies(app_type, dict.fromkeys(ids))
