"""The Rust egress lockdown compiles in a copy of Python's address tables.

They are generated by
`backend/native/lumen-sandbox-proxy/scripts/export_ip_ranges.py` from
`ipaddress`, which tracks the IANA special-purpose registries and changes
between Python releases.

These tests fail when the committed copy drifts. A stale copy means the Rust
proxy would relay a sandbox to a range Python calls internal — a database, a
cache, or the cloud metadata endpoint.
"""

import ipaddress
import json
import subprocess
import sys
from pathlib import Path

_CRATE_DIR = Path(__file__).resolve().parents[4] / "native" / "lumen-sandbox-proxy"
_RANGES_PATH = _CRATE_DIR / "data" / "ip_special_ranges.json"
_SCRIPT = _CRATE_DIR / "scripts" / "export_ip_ranges.py"
_GENERATOR = "backend/native/lumen-sandbox-proxy/scripts/export_ip_ranges.py"
_REGENERATE = f"Regenerate it with: uv run python {_GENERATOR}"


def _exported() -> dict:
    assert _RANGES_PATH.is_file(), f"{_RANGES_PATH} is missing; run {_GENERATOR}"
    loaded = json.loads(_RANGES_PATH.read_text(encoding="utf-8"))
    assert isinstance(loaded, dict)
    return loaded


def test_exported_ranges_match_this_python(tmp_path: Path) -> None:
    exported = _exported()
    expected = _regenerate_into(tmp_path / "ip_special_ranges.json")

    if exported["python_version"] != expected["python_version"]:
        raise AssertionError(
            f"The Rust lockdown's address tables were exported from Python "
            f"{exported['python_version']}, this is "
            f"{expected['python_version']}. {_REGENERATE}"
        )
    assert exported == expected, (
        f"The Rust lockdown's address tables are stale. {_REGENERATE}"
    )


def test_every_exported_block_is_a_real_network() -> None:
    """A block Rust cannot parse would silently drop out of the deny set."""
    for family in ("v4", "v6"):
        version = 4 if family == "v4" else 6
        for key in ("private", "private_exceptions", "not_global"):
            for block in _exported()[family][key]:
                network = ipaddress.ip_network(block)
                assert network.version == version, (
                    f"{block} is listed under {family} but is IPv{network.version}"
                )


def test_the_ranges_that_would_be_missed_by_an_rfc1918_check_are_present() -> None:
    """The ranges the lockdown exists for, named so a regression is legible.

    A deny-list of RFC 1918 alone would relay a sandbox to the cloud metadata
    endpoint and to every EKS pod under custom networking.
    """
    exported = _exported()
    v4_blocks = set(exported["v4"]["private"]) | set(exported["v4"]["not_global"])
    for block in ("169.254.0.0/16", "100.64.0.0/10", "127.0.0.0/8", "0.0.0.0/8"):
        assert block in v4_blocks, f"{block} is missing from the deny set"

    v6_blocks = set(exported["v6"]["private"])
    for block in ("::1/128", "fc00::/7", "fe80::/10"):
        assert block in v6_blocks, f"{block} is missing from the deny set"


def _regenerate_into(destination: Path) -> dict:
    """Run the real generator command into `destination` and read it back.

    Running the command rather than importing it keeps the test honest about
    the fix it prescribes, and keeps the type checker able to see every import.
    """
    result = subprocess.run(  # noqa: S603
        [sys.executable, str(_SCRIPT), str(destination)],
        capture_output=True,
        text=True,
        check=False,
    )
    assert result.returncode == 0, f"{_GENERATOR} failed:\n{result.stderr}"
    loaded = json.loads(destination.read_text(encoding="utf-8"))
    assert isinstance(loaded, dict)
    return loaded
